services:
  app:
    image: flight-front
    volumes:
      - ./flights-front/:/usr/src/app
      - ./flights-front/node_modules:/usr/src/app/node_modules

    # no ports here!

  server:
      image: flight-back
      volumes:
        - ./flights-back/:/usr/src/app


  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80 # this is needed
    container_name: reverse-proxy
    depends_on:
      - app
  
volumes:
  node_modules: