### Add a new HealthCheck entry
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "type": "HealthCheck",
  "description": "Routine health check",
  "date": "2025-04-29",
  "specialist": "Dr. Smith",
  "healthCheckRating": 0
}